# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the features branch
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install JDK to run Java/Kotlin files
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Configure CodeArtifact
        id: codeartifact
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ vars.DOMAIN }} \
            --domain-owner ${{ vars.OWNER }} \
            --region ${{ vars.REGION }} \
            --query authorizationToken \
            --output text)

          export CODEARTIFACT_REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain ${{ vars.DOMAIN }} \
            --domain-owner ${{ vars.OWNER }} \
            --repository ${{ vars.REPOSITORY }} \
            --format maven \
            --region ${{ vars.REGION }} \
            --query repositoryEndpoint \
            --output text)

          echo "token=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_OUTPUT
          echo "url=$CODEARTIFACT_REPO_URL" >> $GITHUB_OUTPUT

      # Create environment files to download dependencies from AWS CodeArtifact
      - name: Rebuild private gradle file and create temporary codeartifact file
        env:
          PRIVATE_GRADLE_FILE: ${{ secrets.CODEARTIFACT_GRADLE_FILE }}
        run: |
          set -euo pipefail
          mkdir -p ~/.gradle
          # Writing file as it is, without substitutions
          printf '%s' "$PRIVATE_GRADLE_FILE" > ~/.gradle/init.gradle.kts
          chmod 600 ~/.gradle/init.gradle.kts
          echo "Creating temporary file..."
          touch .use-codeartifact
          ls -la

      # Grant permission to access Gradle
      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      # Run all unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
        env:
          CODEARTIFACT_TOKEN: ${{ steps.codeartifact.outputs.token }}
          CODEARTIFACT_URL: ${{ steps.codeartifact.outputs.url }}

      # Generate Jacoco Report for code coverage
      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport
        env:
          CODEARTIFACT_TOKEN: ${{ steps.codeartifact.outputs.token }}
          CODEARTIFACT_URL: ${{ steps.codeartifact.outputs.url }}

      # Upload a code coverage report to build folder
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/html

      # Removing all temporary files added for environment purposes
      - name: Remove temporary file
        if: always()    # eseguito anche se i test falliscono
        run: |
          echo "Deleting temporary file..."
          rm -f .use-codeartifact
          rm -f ~/.gradle/init.gradle.kts
          ls -la
