name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install JDK to run Java/Kotlin files
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      # Configure CodeArtifact access using AWS CLI
      - name: Configure CodeArtifact
        id: codeartifact
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ vars.DOMAIN }} \
            --domain-owner ${{ vars.OWNER }} \
            --region ${{ vars.REGION }} \
            --query authorizationToken \
            --output text)

          export CODEARTIFACT_REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain ${{ vars.DOMAIN }} \
            --domain-owner ${{ vars.OWNER }} \
            --repository ${{ vars.REPOSITORY }} \
            --format maven \
            --region ${{ vars.REGION }} \
            --query repositoryEndpoint \
            --output text)

          echo "token=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_OUTPUT
          echo "url=$CODEARTIFACT_REPO_URL" >> $GITHUB_OUTPUT

      # Export environment variables for CodeArtifact as global variables, accessible to all steps
      - name: Export CodeArtifact env
        run: |
          echo "CODEARTIFACT_TOKEN=${{ steps.codeartifact.outputs.token }}" >> $GITHUB_ENV
          echo "CODEARTIFACT_URL=${{ steps.codeartifact.outputs.url }}" >> $GITHUB_ENV

      # Create environment files to download dependencies from AWS CodeArtifact
      - name: Rebuild private gradle file and create temporary codeartifact file
        env:
          PRIVATE_GRADLE_FILE: ${{ secrets.CODEARTIFACT_GRADLE_FILE }}
        run: |
          set -euo pipefail
          mkdir -p ~/.gradle
          # Writing file as it is, without substitutions
          printf '%s' "$PRIVATE_GRADLE_FILE" > ~/.gradle/init.gradle.kts
          chmod 600 ~/.gradle/init.gradle.kts
          echo "Creating temporary file..."
          touch .use-codeartifact
          ls -la

      # Grant permission to access Gradle
      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      # Run all unit tests
      - name: Run unit tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BACKEND_URL: ${{ vars.BACKEND_PUBLIC_DOMAIN }}
          MAVEN_DOMAIN: ${{ vars.DOMAIN }}
          MAVEN_OWNER: ${{ vars.OWNER }}
          MAVEN_URL: ${{ steps.codeartifact.outputs.url }}
        run: |
          ( while sleep 30; do echo "⏳ Tests running..."; done ) &
          KEEPALIVE_PID=$!
          ./gradlew testDebugUnitTest \
            --stacktrace \
            --no-daemon \
            --max-workers=1
          kill $KEEPALIVE_PID

      # Enable KVM for hardware acceleration (for Android emulator process)
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Run android tests on core:database module
      - name: Run androidTest (core:database)
        uses: reactivecircus/android-emulator-runner@v2
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BACKEND_URL: ${{ vars.BACKEND_PUBLIC_DOMAIN }}
          MAVEN_DOMAIN: ${{ vars.DOMAIN }}
          MAVEN_OWNER: ${{ vars.OWNER }}
          MAVEN_URL: ${{ steps.codeartifact.outputs.url }}
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_7
          emulator-boot-timeout: 600
          emulator-options: >
            -no-window 
            -no-audio 
            -no-boot-anim
            -no-snapshot
            -no-snapshot-load
            -no-snapshot-save
            -gpu swiftshader_indirect
            -camera-back none
            -camera-front none
          disable-animations: true
          script: ./gradlew :core:database:connectedDebugAndroidTest

      # Generate Jacoco Report for code coverage
      - name: Generate JaCoCo report
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BACKEND_URL: ${{ vars.BACKEND_PUBLIC_DOMAIN }}
          MAVEN_DOMAIN: ${{ vars.DOMAIN }}
          MAVEN_OWNER: ${{ vars.OWNER }}
          MAVEN_URL: ${{ steps.codeartifact.outputs.url }}
        run: ./gradlew jacocoAggregateReport

      # installing xmllint to read coverage file
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      # Calculate a code coverage percentage to be shown to developer on PR
      - name: Extract coverage percentage
        id: coverage
        run: |
          REPORT_FILE="build/reports/jacoco/jacocoAggregateReport.xml"

          if [ ! -f "$REPORT_FILE" ]; then
            echo "Report XML not found!"
            exit 1
          fi

          MISSED=$(xmllint --xpath "string(/report/counter[@type='LINE']/@missed)" $REPORT_FILE)
          COVERED=$(xmllint --xpath "string(/report/counter[@type='LINE']/@covered)" $REPORT_FILE)

          echo "MISSED=$MISSED"
          echo "COVERED=$COVERED"

          if [ -z "$MISSED" ] || [ -z "$COVERED" ]; then
            echo "Counters not found, setting coverage=0"
            echo "coverage=0" >> $GITHUB_OUTPUT
            exit 0
          fi

          TOTAL=$((MISSED + COVERED))

          if [ "$TOTAL" -eq 0 ]; then 
            COVERAGE=0
          else
            COVERAGE=$(( 100 * COVERED / TOTAL ))
          fi

          echo "Coverage: $COVERAGE%"
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

      # We keep the PR check just to avoid errors
      - name: Comment coverage on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## 📊 Code Coverage Report

            **Coverage:** ${{ steps.coverage.outputs.coverage }}%  
            **Required:** ${{ vars.COVERAGE_THRESHOLD }}%

            ➡️ Open the link below and download the **coverage-report** artifact.
            🔗 **Coverage report artifact:**  
            [Download coverage report](
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            )

            ### Merge checklist
            - [ ] Coverage ≥ ${{ vars.COVERAGE_THRESHOLD }}%
          comment_tag: coverage-comment

      # This will break the pipeline if the coverage is under threshold
      - name: Check coverage threshold
        if: always()
        run: |
          COVERAGE=${{ steps.coverage.outputs.coverage }}
          THRESHOLD=${{ vars.COVERAGE_THRESHOLD }}

          echo "Coverage: $COVERAGE%"
          echo "Threshold: $THRESHOLD%"

          if [ "$COVERAGE" -lt "$THRESHOLD" ]; then
            echo "❌ Coverage below threshold"
            exit 1
          else
            echo "✅ Coverage meets threshold"
          fi
      
      # Upload a code coverage report to build folder
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/aggregate

      # Removing all temporary files added for environment purposes
      - name: Remove temporary file
        if: always()    # eseguito anche se i test falliscono
        run: |
          echo "Deleting temporary file..."
          rm -f .use-codeartifact
          rm -f ~/.gradle/init.gradle.kts
          ls -la
